#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Oct 18 11:06:48 2019
Script for examining O3 changes in 2009. What was the cause and is 
the data from this period usable?
@author: matthewrowlinson
"""
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
plt.style.use('seaborn-darkgrid')
plt.rcParams['figure.figsize'] = (7, 7)
filepath  = '/Users/matthewrowlinson/Documents/NCAS_CVAO/CVAO_datasets/'
savepath  = '/Users/matthewrowlinson/Documents/NCAS_CVAO/plots/'

filen = filepath+'20191007_CV_Merge.csv'
df = pd.read_csv(filen, index_col=0,dtype={'Airmass':str},engine='python')
df.index = pd.to_datetime(df.index,format='%d/%m/%Y %H:%M')

filen = filepath+'cv_ovocs_2018_M_Rowlinson.csv'
odf = pd.read_csv(filen, index_col=0,engine='python')
odf.index = pd.to_datetime(odf.index,format='%d/%m/%Y %H:%M')

cols = list(df) ; ocols = list(odf)
for col in cols:
    try:
        df[col] = df[col].loc[~(df[col] <= 0.)]
    except:
        pass
for col in ocols:
    odf = odf.loc[~(odf[col] <= 0.)]
cols  = cols+ocols
   
hourly = df.resample('H').mean()
daily = df.resample('D').mean()
monthly = df.resample('M').median()
yearly= df.resample('Y').mean()

ohourly = odf.resample('H').mean()
odaily = odf.resample('D').mean()
omonthly = odf.resample('M').median()
oyearly= odf.resample('Y').mean()

hourly = pd.concat([hourly,ohourly],axis=1,sort=False)
daily = pd.concat([daily,odaily],axis=1,sort=False)
monthly = pd.concat([monthly,omonthly],axis=1,sort=False)
yearly = pd.concat([yearly,oyearly],axis=1,sort=False)

years = np.arange(2006, 2006+len(yearly.index))
colors = ['#e5f5e0','#c7e9c0','R','#74c476','#41ab5d',\
              '#7fcdbb','#41b6c4','#1d91c0',\
              '#225ea8','b','#253494','#081d58','k']
style=['-','--','-.',':']
## Choose the species - one at a time currently
species = 'RAINFALL (mm)'
## chose period to plot, starts at 2006, runs to 2019
start_year = '2009' ; end_year = '2010'
if species == 'O3' or species == 'meoh' or 'ace' in species:
    unit = ''
elif species == 'CO' or species == 'CH4':
    unit = ' (ppbV)'
elif '(mm)' in species:
    unit=''
else:
    unit = ' (pptV)'
data = hourly[species+unit][start_year:]
years = len((data.resample('Y').mean()).index.year)

## method one - centered moving average
ds1 = data.rolling(window=12,center=True).mean()
## method two - seasonal differencing 
def difference(dataset, interval=1):
	diff = list()
	for i in range(interval, len(dataset)):
		value = dataset[i] - dataset[i - interval]
		diff.append(value)
	return diff
## method three - subtracting monthly average for each observation
mean = data.mean()
std = data.std()
monmean = data.groupby(data.index.month).mean()

## plotting results of all methods on one plot
plt.rcParams['figure.figsize'] = (12, 4)
plt.scatter(data.index, data, label='Observations',color='darkgrey')#,linestyle='--')

plt.ylabel(species+unit)
plt.legend()
#plt.savefig(savepath+species+'_seasonality.png')
#plt.close()
plt.show()